export type {
  SandboxFilesystemConfig,
  SandboxIgnoreViolations,
  SandboxNetworkConfig,
  SandboxSettings,
} from '../sandboxTypes.js'
export * from './coreTypes.generated.js'
export type { NonNullableUsage } from './sdkUtilityTypes.js'
export const HOOK_EVENTS = [
  'BeforeToolInvoke',
  'AfterToolInvoke',
  'AfterToolInvokeFailure',
  'OnNotification',
  'OnUserPrompt',
  'OnSessionStart',
  'SessionEnd',
  'OnAgentStop',
  'OnAgentStopFailure',
  'SubagentStart',
  'SubagentStop',
  'BeforeContextCompact',
  'AfterContextCompact',
  'OnPermissionRequest',
  'PermissionDenied',
  'Setup',
  'TeammateIdle',
  'TaskCreated',
  'TaskCompleted',
  'Elicitation',
  'ElicitationResult',
  'ConfigChange',
  'WorktreeCreate',
  'WorktreeRemove',
  'InstructionsLoaded',
  'CwdChanged',
  'FileChanged',
] as const
export const EXIT_REASONS = [
  'clear',
  'resume',
  'logout',
  'prompt_input_exit',
  'other',
  'bypass_permissions_disabled',
] as const
